CREATE TABLE ALUNOS (
  NUMERO_MATRICULA INTEGER NOT NULL,
  CPF VARCHAR NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  NOME VARCHAR(150) NOT NULL,
  DATA_INGRESSO DATETIME NOT NULL,
  ENDERECO VARCHAR(150),
  SEXO CHAR(1) NOT NULL,
  CONSTRAINT PK_ALUNOS PRIMARY KEY (NUMERO_MATRICULA),
  CONSTRAINT AK_ALUNOS1 UNIQUE (CPF),
  CONSTRAINT AK_ALUNOS2 UNIQUE (EMAIL)
)

--Integridade de domínio
ALTER TABLE ALUNOS
ADD CONSTRAINT CK_SEXO CHECK (SEXO IN ('F', 'M'))

