CREATE TABLE ESTADOS (
  UF		CHAR(2)		NOT NULL,
  NOME		VARCHAR(40)	NOT NULL,
  REGIAO	CHAR(2)		NOT NULL,
  CONSTRAINT PK_ESTADOS PRIMARY KEY (UF))

CREATE TABLE CIDADES (
  COD_CIDADE	INTEGER		NOT NULL,
  NOME			VARCHAR(60)	NOT NULL,
  CONSTRAINT PK_CIDADES PRIMARY KEY (COD_CIDADE))

ALTER TABLE CIDADES ADD UF CHAR(2) NOT NULL

ALTER TABLE CIDADES 
ADD CONSTRAINT FK_EST_CID FOREIGN KEY (UF) REFERENCES ESTADOS (UF)

SELECT *
  FROM ESTADOS

SELECT *
  FROM CIDADES

INSERT INTO ESTADOS
VALUES ('SC', 'SANTA CATARINA', 'S'),
('RS', 'RIO GRANDE DO SUL', 'S'),
('PR', 'PARANA', 'S')


INSERT INTO CIDADES VALUES
(1, 'CHAPECO', 'SC'),
(2, 'MARINGA', 'PR'),
(3, 'PELOTAS', 'RS')