name: CI para Conversao Temperatura

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 03_devops_basico/conversao-temperatura

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup do NodeJS
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 16.14.0